# Generated by Django 3.1.7 on 2021-02-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210228_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
    ]
